# EXTRACT DATA FROM API
# This script reads a CSV file in GNU R.
# This script has been generated by SocSci and modified by Eurofound. 

#setwd("C:/Users/mwi/OneDrive - Eurofound/covid_survey/")

# API link of the SocSci database of the Eurofound survey. API token is confidential and stored in secrets file.
source("secrets.R")
ds_file = paste0("https://s2survey.net/eurofound/?act=", token)

source("app_web/get_data_from_api.R")

ds <- get_data_from_api(ds_file)

#Saving the raw data
save(ds, file="data/ds_raw_0105.Rda")
